# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentari',
            name='usuari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentari', to='usuaris.Perfil'),
        ),
        migrations.AlterField(
            model_name='comentari',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
