# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estil_musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_estil', models.CharField(max_length=150)),
                ('descripcio_estil', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Forma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fusta_c',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fusta_c', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fusta_d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fusta_d', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_grup', models.CharField(max_length=150)),
                ('descripcio_grup', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Guitarra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarra.Estil_musica')),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarra.Forma')),
                ('fusta_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarra.Fusta_c')),
                ('fusta_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarra.Fusta_d')),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarra.Grup')),
            ],
        ),
        migrations.CreateModel(
            name='N_cordes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pastilles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastilles', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tremolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tremolo', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='guitarra',
            name='n_cordes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarra.N_cordes'),
        ),
        migrations.AddField(
            model_name='guitarra',
            name='pastilles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarra.Pastilles'),
        ),
        migrations.AddField(
            model_name='guitarra',
            name='tremolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarra.Tremolo'),
        ),
    ]
