# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarra', '0002_guitarra_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarra',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
