# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarra', '0003_auto_20170504_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guitarra',
            old_name='image',
            new_name='imatge',
        ),
        migrations.AddField(
            model_name='grup',
            name='imatge',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
