# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarra', '0006_auto_20170515_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitarra',
            name='color',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
