# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarra', '0007_guitarra_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarra',
            name='estil',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarra',
            name='forma',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarra',
            name='fusta_c',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarra',
            name='fusta_d',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarra',
            name='grup',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarra',
            name='n_cordes',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarra',
            name='pastilles',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarra',
            name='tremolo',
            field=models.CharField(max_length=100),
        ),
    ]
