# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarra', '0008_auto_20170515_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitarra',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
