# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarra', '0011_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tremolo',
            name='tremolo',
            field=models.CharField(max_length=5),
        ),
    ]
