# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guitarra', '0012_auto_20170515_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarra',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarra.Color'),
        ),
        migrations.AlterField(
            model_name='guitarra',
            name='forma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarra.Forma'),
        ),
        migrations.AlterField(
            model_name='guitarra',
            name='fusta_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarra.Fusta_c'),
        ),
        migrations.AlterField(
            model_name='guitarra',
            name='fusta_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarra.Fusta_d'),
        ),
        migrations.AlterField(
            model_name='guitarra',
            name='n_cordes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarra.N_cordes'),
        ),
        migrations.AlterField(
            model_name='guitarra',
            name='pastilles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarra.Pastilles'),
        ),
        migrations.AlterField(
            model_name='guitarra',
            name='tremolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarra.Tremolo'),
        ),
    ]
