# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarra', '0013_auto_20170515_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='n_cordes',
            name='num',
            field=models.CharField(max_length=100),
        ),
    ]
