# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 18:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guitarra', '0015_auto_20170515_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitarra',
            name='preu',
            field=models.CharField(default=datetime.datetime(2017, 5, 15, 18, 43, 37, 412692, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
