# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarra', '0018_auto_20170515_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarra',
            name='preu',
            field=models.IntegerField(null=True),
        ),
    ]
