# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-16 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitarra', '0019_auto_20170515_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitarra',
            name='descripcio_guitarra',
        ),
    ]
