# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-16 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarra', '0020_remove_guitarra_descripcio_guitarra'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitarra',
            name='descripcio_guitarra',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
