# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarra', '0022_auto_20170603_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estil_musica',
            name='descripcio_estil',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='grup',
            name='descripcio_grup',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='guitarra',
            name='descripcio_guitarra',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
